seed_everything: 8089
trainer:
  accelerator: auto
  strategy: ddp_find_unused_parameters_true
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger:
  - class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: .out/tb/1024
      name: convnext+asl+1024+3e-05/task1/stage-1
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: checkpoints/backbones/task1/ckpts/1024/convnext+asl+1024+3e-05
      filename: '{epoch:02d}-{val_loss:.4f}-{val_ap:.5f}'
      save_top_k: 1
      save_last: true
      monitor: val_ap
      mode: max
  - class_path: src.callbacks.chexpert_pseudo_callback.ChexpertWriter
    init_args:
      write_interval: epoch
      chexpert_train_df_path: data/chexpert/CheXpert-v1.0/train_expanded.csv
      chexpert_pseudo_train_df_path: .tmp/pseudolabels/chexpert/task1/convnext+asl+1024+3e-05/train_expanded_pseudo.csv
      num_classes: 40
  - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    init_args:
      monitor: val_ap
      mode: max
      patience: 10
      min_delta: 0.002
  fast_dev_run: false
  overfit_batches: 0.0
  val_check_interval: 0.25
  num_sanity_val_steps: 2
  accumulate_grad_batches: 1
  gradient_clip_val: null
  deterministic: null
  benchmark: true
  max_epochs: 150
model:
  lr: 3.0e-05
  embedding: null
  zsl: 0
  classes: &id001
  - Adenopathy
  - Atelectasis
  - Azygos Lobe
  - Calcification of the Aorta
  - Cardiomegaly
  - Clavicle Fracture
  - Consolidation
  - Edema
  - Emphysema
  - Enlarged Cardiomediastinum
  - Fibrosis
  - Fissure
  - Fracture
  - Granuloma
  - Hernia
  - Hydropneumothorax
  - Infarction
  - Infiltration
  - Kyphosis
  - Lobar Atelectasis
  - Lung Lesion
  - Lung Opacity
  - Mass
  - Nodule
  - Normal
  - Pleural Effusion
  - Pleural Other
  - Pleural Thickening
  - Pneumomediastinum
  - Pneumonia
  - Pneumoperitoneum
  - Pneumothorax
  - Pulmonary Embolism
  - Pulmonary Hypertension
  - Rib Fracture
  - Round(ed) Atelectasis
  - Subcutaneous Emphysema
  - Support Devices
  - Tortuous Aorta
  - Tuberculosis
  loss_init_args:
    type: asl
    class_instance_nums:
    - 3409
    - 65376
    - 199
    - 4239
    - 74738
    - 168
    - 15371
    - 37256
    - 3661
    - 29628
    - 1169
    - 2803
    - 11568
    - 2965
    - 3986
    - 646
    - 727
    - 10087
    - 778
    - 129
    - 2338
    - 77482
    - 5288
    - 7531
    - 34292
    - 66401
    - 616
    - 3272
    - 704
    - 46660
    - 516
    - 13858
    - 1631
    - 903
    - 8919
    - 172
    - 2046
    - 86079
    - 3336
    - 2078
    total_instance_num: 258871
  model_type: convnext
  model_init_args:
    num_classes: 40
    model_name: convnext_small.fb_in22k_ft_in1k_384
    pretrained: true
data:
  dataloader_init_args:
    batch_size: 16
    num_workers: 8
    pin_memory: true
    persistent_workers: true
  datamodule_cfg:
    predict_pseudo_label: null
    use_pseudo_label: false
    loader_type: single
    data_dir: data/
    resized_dir: data-resized/
    train_df_path: data/cxr-lt-iccv-workshop-cvamd/2.0.0/cxr-lt-2024/train_labeled.csv
    task1_df_path: data/cxr-lt-iccv-workshop-cvamd/2.0.0/cxr-lt-2024/development_labeled_task1.csv
    task2_df_path: data/cxr-lt-iccv-workshop-cvamd/2.0.0/cxr-lt-2024/development_labeled_task2.csv
    zero_shot_df_path: data/cxr-lt-iccv-workshop-cvamd/2.0.0/cxr-lt-2024/development_task3.csv
    vinbig_train_df_path: data/vinbig-cxr/train_expanded.csv
    vinbig_pseudo_train_df_path: .tmp/pseudolabels/vinbig/task1/convnext+asl+1024+3e-05/train_expanded_pseudo.csv
    nih_train_df_path: data/nih-cxr/train_expanded.csv
    nih_pseudo_train_df_path: .tmp/pseudolabels/nih/task1/convnext+asl+1024+3e-05/train_expanded_pseudo.csv
    chexpert_train_df_path: data/chexpert/CheXpert-v1.0/train_expanded.csv
    chexpert_pseudo_train_df_path: .tmp/pseudolabels/chexpert/task1/convnext+asl+1024+3e-05/train_expanded_pseudo.csv
    pred_df_path: data/cxr-lt-iccv-workshop-cvamd/2.0.0/cxr-lt-2024/test_labeled_task1.csv
    val_split: 0.1
    seed: 8089
    size: 1024
    classes: *id001
ckpt_path: null
